### ISSUE TITLE
node version?

### ISSUE THREAD

**Issue by ypli0629** [song940/node-gsm#2]
### I use node v8.9.3,but when I run the example, it cause an error

(node:2681) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Timeout exceeded
(node:2681) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by song940** [comment]
Not node and node version. this library send AT Command to your gsm modem and waiting response in a timeout 5000ms. you can two options to test that:
1. set timeout to a bigger number eg.: 1e5 or 1e6
2. check your device connection and manually send AT command to gsm device use terminal console
