### ISSUE TITLE
是否支持发送中文短信？

### ISSUE THREAD

**Issue by houaq** [song940/node-gsm#3]
如题。
把example里的消息内容直接改成中文好像不行，收到中文是乱码。

**Comment by song940** [comment]
Any questions ?

**Comment by houaq** [comment]
I modified the example/index.js as following:
`modem.open(async () => {

  await modem.reset()
  await modem.sms_mode(1)
  await modem.sms_send(
    '+8613833110268',
    '中文测试This is a test from gsm2',
		'utf8'
  );

});
`
The source file is encoded by utf-8, but problem remains:
![_20180706162617](https://user-images.githubusercontent.com/1428920/42368357-6a574450-8139-11e8-9ce2-0cfebb7c04bd.jpg)

**Comment by song940** [comment]
use PDU mode and try again ?

**Comment by houaq** [comment]
How to set PDU mode? Is there an option?

**Comment by song940** [comment]
[AT Commands Reference Guide](https://github.com/song940/node-gsm/blob/master/docs/AT_Commands_Reference_Guide.pdf)

```
AT+CMGF[= [<mode>]]
Set command selects the format of messages used with send, list, read and write commands.
Parameter:
<mode>
0 - PDU mode, as defined in GSM 3.40 and GSM 3.41 (factory default) 
1 - text mode
Note: issuing AT+CMGF<CR> is the same as issuing the Read command.
Note: issuing AT+CMGF=<CR> is the same as issuing the command AT+CMGF=0<CR>.
```
or

```js
const SMS_MODE = {
  PDU: 0,
  TEXT: 1
};
await modem.sms_mode(SMS_MODE.PDU);
await modem.sms_send('phone number', 'pdu string');
```
