### ISSUE TITLE
Unable to receive SMS

### ISSUE THREAD

**Issue by Kmasterrr** [song940/node-gsm#6]
Hi there! 

I really hope you are still supporting this wonderful package.
I was able to receive an SMS from my raspberry pi via your node package, but i am unable to receive an SMS. I have tried both: 

```
modem.on('+CMTI', msg => {
  console.log('Incoming Message', msg);
});
```

as well as 

```
modem.on('+CMGR', msg => {
  console.log('Incoming Message', msg);
});
```

neither return the SMS i send to the sim card in said pi. Could you assist?

**Comment by VicAMMON** [comment]
Hello.
How to close session with modem ?
Like modem.open()  ... modem.close()

**Comment by song940** [comment]
@Kmasterrr Use [model#sms_read](https://github.com/song940/node-gsm/blob/master/modem.js#L178) or model#sms_list .

**Comment by song940** [comment]
Yes, this module extends [serialport](https://github.com/serialport/node-serialport), so you can use [those methods](https://serialport.io/docs/api-stream#serialport-close) as well.

**Comment by VicAMMON** [comment]
Thank you mach!
